### ISSUE TITLE
import error when using datapackage installed by pip 

### ISSUE THREAD

**Issue by reikkaps** [frictionlessdata/datapackage-py#208] opened 2018-02-05 12:52 UTC
Hi,
currently i am testing the datapackage module (for use in our research data management enviroment). First i tried your examples https://github.com/frictionlessdata/datapackage-py/blob/master/README.md. But
i got an ImportError like this one: 

> Traceback (most recent call last):
>   File "create-datapackage.py", line 3, in <module>
>     from datapackage import Package
>   File "/home/RRZN/kaps/Dokumente/Projekte/dataset-examples/venv/lib/python3.5/site-packages/datapackage/__init__.py", line 10, in <module>
>     from .package import Package
>   File "/home/RRZN/kaps/Dokumente/Projekte/dataset-examples/venv/lib/python3.5/site-packages/datapackage/package.py", line 19, in <module>
>     from tableschema import Storage
>   File "/home/RRZN/kaps/Dokumente/Projekte/dataset-examples/venv/lib/python3.5/site-packages/tableschema/__init__.py", line 10, in <module>
>     from .schema import Schema
>   File "/home/RRZN/kaps/Dokumente/Projekte/dataset-examples/venv/lib/python3.5/site-packages/tableschema/schema.py", line 12, in <module>
>     from .field import Field
>   File "/home/RRZN/kaps/Dokumente/Projekte/dataset-examples/venv/lib/python3.5/site-packages/tableschema/field.py", line 13, in <module>
>     from . import types
>   File "/home/RRZN/kaps/Dokumente/Projekte/dataset-examples/venv/lib/python3.5/site-packages/tableschema/types/__init__.py", line 21, in <module>
>     from .string import cast_string
>   File "/home/RRZN/kaps/Dokumente/Projekte/dataset-examples/venv/lib/python3.5/site-packages/tableschema/types/string.py", line 12, in <module>
>     import rfc3986.validators
> ImportError: No module named 'rfc3986.validators'

Is it a problem of my installation or a problem of the pip-package / python module? And how can i fix it? 

Many thanks for your work, Reiko

**Comment by roll** [comment] 2018-02-12 07:22
@reikkaps 
Hi, probably it's a problem with your installation because I can't reproduce it on a fresh one.

**Comment by reikkaps** [comment] 2018-02-12 08:17
@roll many thanks. i will investigate it further. And btw a fresh source installation from the github repo was sucessful.

**Comment by roll** [comment] 2018-02-12 08:20
@reikkaps 
Great! Related to the `pip` installation - the following should work:

```
mkdir test
cd test
virtualenv .python -p python3
source .python/bin/activate
pip install datapackage
```

Closing for now. Please re-open if needed.

**Closed by roll** 2018-02-12 08:20 UTC
Labels: question, {review}
