### ISSUE TITLE
Add DataPackage.push method

### ISSUE THREAD

**Issue by danfowler** [frictionlessdata/datapackage-py#75] opened 2016-05-01 11:53 UTC
I can load Data Packages via URLs from data.okfn.org (e.g. http://data.okfn.org/data/core/cpi/datapackage.json) or from within the working directory (e.g. ".").  I am having trouble, though, loading directly from GitHub ('https://raw.githubusercontent.com/datasets/cpi/master/datapackage.json') or anywhere else on the filesystem.

In my case, loading works well:

```
import datapackage
dp = datapackage.DataPackage('https://raw.githubusercontent.com/datasets/cpi/master/datapackage.json')
```

But when I try to push to e.g. an SQL database using:

```
push_datapackage(descriptor=dp.metadata,backend='sql',engine=engine)
```

I get the following error:

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/dan/open_knowledge/envs/tutorial/lib/python3.5/site-packages/datapackage/pushpull.py", line 53, in push_datapackage
    data = resource.iter()
  File "/Users/dan/open_knowledge/envs/tutorial/lib/python3.5/site-packages/datapackage/resource.py", line 297, in iter
    raise IOError('Resource\'s data couldn\'t be loaded.')
OSError: Resource's data couldn't be loaded.
```

For the above example of loading from https://raw.githubusercontent.com/datasets/cpi/master/datapackage.json, it seems to be trying to load directly from non-existent "data/cpi.csv" in the working directory and not "https://raw.githubusercontent.com/datasets/cpi/master/data/cpi.csv"

**Comment by roll** [comment] 2016-05-01 12:11
@danfowler 
This is expected behavior for now - when you provide metadata (just a python dict) to `push_datapackage` - tool has no chance to understand it's remote.

**Comment by vitorbaptista** [comment] 2016-05-03 11:25
I think this is a weak point of the current design. The push and pull datapackage methods don't fit with the rest of the code structure yet. Ideally, this should work:

```python
import datapackage
dp = datapackage.DataPackage('https://raw.githubusercontent.com/datasets/cpi/master/datapackage.json')
dp.push(backend='sql', engine=engine)
```

**Comment by danfowler** [comment] 2016-05-03 23:17
@roll I see what you mean.
@vitorbaptista 👍

**Comment by rgrp** [comment] 2016-05-04 20:01
@vitorbaptista @roll this is a more general issue as I understand it that the current library does not compute relative paths for resources correctly given the source url.

This came up in the JS implementation. The DataPackage object needs to check the location where it was originally initiated and then use that in computing the paths for resources which are relative to that original location.

The reason the data.okfn.org link works is that `url` is present on each resource (in fact violating the spec because both path and url are present - this is an overhang from an old hack on data.okfn.org). If we did not have url the code would fail.

If this analysis is correct I suggest we rename this issue to the more precise e.g.: "Handle path on resources not just url"

**Comment by roll** [comment] 2016-05-05 09:43
It by design we can't do `push_datapackage(descriptor=dp.metadata, backend='sql', engine=engine)`for now because it's was a transitional tool. It just creates own copy of datapackage (procedure approach). So we're going to improve this behavior in a future (see object-oriented approach - https://github.com/frictionlessdata/datapackage-py/issues/75#issuecomment-216500408). So it's known issue/potential enhancement.

But I'm not sure what's a problem with a core `datapackage.DataPackage`? From my experience of this tool usage it works equal good for local, remote (with path adjusting I suppose) etc datapackages (cc @vitorbaptista ).

**Comment by roll** [comment] 2016-05-05 09:58
It works:

```
import datapackage
url = 'https://raw.githubusercontent.com/datasets/currency-codes/master/datapackage.json'
dp = datapackage.DataPackage(url)
print(dp.resources[0].data)
```

Or @rgrp you mean it also should recalculate `dp.metadata`?

**Comment by rgrp** [comment] 2016-05-05 21:56
@roll ah ok - so it does work correctly with DataPackage object but the pass through to storage is the issue. Great!

Still suggest we rename issue so it is clear what the actual issue is so we don't forget. Will leave that to your or @vitorbaptista 😄

**Comment by vitorbaptista** [comment] 2016-05-06 12:57
@rgrp Just to add to what @roll said, the problem here is that @danfowler was passing `dp.metadata`, which is just a dict. There's no indication of where it came from. However, the `DataPackage` instance itself knows its base path and can calculate relative paths for the resources, which is why I think the `push_datapackage` and `pull_datapackage` needs to live inside the `DataPackage` class.

**Comment by rgrp** [comment] 2016-05-06 13:07
@vitorbaptista got you and that makes sense. Let's add this to the next sprint.

**Comment by roll** [comment] 2017-03-21 15:23
MERGED
https://github.com/frictionlessdata/datapackage-py/issues/132

Current `push/pull_datapackage` API will not be fixed. There will be an updated API to solve this problem. Merging this issue to general re-implementation tracker.

**Closed by roll** 2017-03-21 15:23 UTC
Labels: feature, planned
