### ISSUE TITLE
datapackage-py validate is not strict enough

### ISSUE THREAD

**Issue by scls19fr** [frictionlessdata/datapackage-py#105] opened 2016-08-29 19:54 UTC
Hello,

https://github.com/datasets/gdp/tree/4149e0b5612719d6a1332edf868cda634b49781a is said to be an invalid datapackage
see https://github.com/datasets/gdp/issues/5

but

``` python
import datapackage
dp = datapackage.DataPackage('http://data.okfn.org/data/core/gdp/datapackage.json')
dp.validate()
```

doesn't raise any exception.

`validate` should be more strict

Same with 
https://github.com/frictionlessdata/datapackage-validate-js/issues/12

Kind regards

**Comment by danfowler** [comment] 2016-08-29 20:12
Hi @scls19fr, thanks for raising this.  One way to look at this is that the issue is not so much with the libraries, but rather with the [JSON Schemas](http://json-schema.org/) that we're validating against.  Currently, `datapackage.json` files are validated using the JSON Schemas listed here: https://github.com/frictionlessdata/schemas.  The JSON Table Schema JSON Schema (say that three times fast) simply checks whether `format` is a "string" or not, but the validation of the `format` field should actually be dependent on the value of the `type` field.

There does seem to be a way to do this sort of conditional validation in JSON Schema (see [this answer on SO](http://stackoverflow.com/questions/9029524/json-schema-specify-field-is-required-based-on-value-of-another-field)).  Given that `format` and `type` validation of CSV is such a core part of our effort, this does seem to be something worth fixing.  I'd be curious to hear your thoughts :).

**Comment by roll** [comment] 2017-03-21 12:54
@scls19fr 
I'm marking it's WONTFIX for now. 

New version of specs (v1) now allow:
- {PATTERN}: The value can be parsed according to {PATTERN}, which MUST follow the date formatting syntax of C / Python strptime.

Checking this pattern seems is out of scope for spec implementation library because spec say nothing concrete about this pattern and just point to another software (`strptime`) which could have different behavior on different systems. 

---

Also there is goodtables (https://github.com/frictionlessdata/goodtables-py) to do all kind of data validations. So it will find error in data in field with invalid date pattern.

**Closed by roll** 2017-03-21 12:54 UTC
Labels: bug, planned
